spring.application.name=ccapp-backend
server.port=8081

# PostgreSQL Connection (Container: cc-app, DB: ccapp_db, Port: 8081)
spring.datasource.url=jdbc:postgresql://localhost:5432/cc_app
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Custom JWT Secret (256-bit Hex Key) & Expiration (24 Hours)
ccapp.app.jwtSecret=dGhpcy1pcy1hLXZlcnktc2VjdXJlLXNlY3JldC1rZXktZm9yLWNjYXAtYmFja2VuZC1hcHBsaWNhdGlvbi1zZWN1cml0eQ==
ccapp.app.jwtExpirationMs=86400000